### ISSUE TITLE
［BUG］HTTP服务请求失败

### ISSUE THREAD

**Issue by cnrenil** [cnlimiter/onebot-mirai#12]
# 问题描述

开启http服务，端口6700，添加accessToken，timeout调3或者0，http无效
使用curl
```
curl -v --header "Content-Type: application/json" --header "Accept: application/json, text/plain, */*" --header "Authorization: Bearer zuiX1xJcwIYW5lzf" --user-agent "axios/0.27.2" --data-binary '{"auto_escape":true,"message":"UptimeKuma Alert: OneBot 通知（1） Testing","message_type":"private","user_id":"2484443126"}' http://0.0.0.0:6700/send_msg
```
显示服务无回应。
预期显示
```
{"status":"ok","retcode":0,"data":{"ClassType":"MessageData","message_id":-2113871920},"echo":null}
```
状态码`200`

# 问题背景

可能导致问题的插件：Control插件
可能导致问题的版本：2.16.0

目前暂时使用
[onebot-kotlin](https://github.com/yyuueexxiinngg/onebot-kotlin)
项目做临时方案

**Comment by cnlimiter** [comment]
并不支持表单请求，请使用json格式
{
    "action": "终结点名称, 例如 'send_group_msg'",
    "params": {
        "参数名": "参数值",
        "参数名2": "参数值"
    },
    "echo": "'回声', 如果指定了 echo 字段, 那么响应包也会同时包含一个 echo 字段, 它们会有相同的值"
}

**Comment by cnrenil** [comment]
> 并不支持表单请求，请使用json格式
> ```json5
> {
>     "action": "终结点名称, 例如 'send_group_msg'",
>     "params": {
>         "参数名": "参数值",
>         "参数名2": "参数值"
>     },
>     "echo": "'回声', 如果指定了 echo 字段, 那么响应包也会同时包含一个 echo 字段, 它们会有相同的值"
> }
> ```

好吧，我改一下推送代码。。。🤣
