### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by smoadrareun** [cnlimiter/onebot-mirai#5]
期待大佬能实现反向websocket连接功能

**Comment by cnlimiter** [comment]
初步完成，计划再做个指令进行反向ws连接，多个反向ws连接的逻辑还未完成

**Comment by SherkeyXD** [comment]
现在反向 ws 可用了吗（

**Comment by cnlimiter** [comment]
> 现在反向 ws 可用了吗（

在写官方协议转换

**Comment by cnlimiter** [comment]
> 现在反向 ws 可用了吗（

大概可以用了吧。

**Comment by cnlimiter** [comment]
有没有已经用上的，反馈一下，还有什么要完善的呢

**Comment by SherkeyXD** [comment]
> 有没有已经用上的，反馈一下，还有什么要完善的呢

似乎带换行符的消息会被分割为多条消息

比如 `test1\ntest2` 会被拆成 `test1` 和 `test2` 两条

**Comment by Shiro-ko** [comment]
> 有没有已经用上的，反馈一下，还有什么要完善的呢

老哥 我目前用的这个来ws到littlePaimon项目，目前来说文字消息好像没问题，图片消息不能发送；是需要更改ws_reverse下的postMessageFormat属性吗？我看到是string，littlePaimon那边发送消息时是报的AttributeError: 'ImageDraw' object has no attribute 'textsize'
